# Funding options for Automate

github: # Add your GitHub username here
# patreon: # Add your Patreon username
# open_collective: # Add your Open Collective username
# ko_fi: # Add your Ko-fi username
# custom: ['https://paypal.me/yourlink', 'https://www.buymeacoffee.com/yourlink']
